version: '2'

services:
  pulsar-monitor:
    image: 'kafkaesqueio/pulsar-ops-monitor:0.27'
    ports:
      - '8080:8080'
    volumes:
      - './config/pulsar-ca.cert:/etc/ssl/certs/ca-bundle.crt'
      - './config/runtime.yml:/config/runtime.yml'
