version: '3'

services:
  pulsar-monitor:
    image: 'kafkaesqueio/pulsar-monitor:1.0.5'
    ports:
      - '8080:8080'
    volumes:
      - './config/kesque-pulsar.cert:/etc/ssl/certs/ca-bundle.crt'
      - './config/runtime.yml:/config/runtime.yml'
