---
prometheusConfig:
  port: ":8080"
  exposeMetrics: true
slackConfig:
  alertUrl: required
sitesConfig:
  sites:
  - url: https://kafkaesque.io/plans
    name: plans
    intervalSeconds: 30
    responseSeconds: 15
    statusCode: 200
    retries: 3
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 300
      CeilingInMovingWindow: 6
  - url: https://kafkaesque.io/wp-login.php?action=register
    name: auth0_register
    intervalSeconds: 30
    responseSeconds: 15
    statusCode: 200
    retries: 3
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 300
      CeilingInMovingWindow: 6
opsGenieConfig:
  intervalSeconds: 180
  heartbeatKey: GenieKey key for heartbeat
  alertKey: GenieKey api key to generate alerts or incidents
pulsarOpsConfig:
  intervalSeconds: 120
  masterToken: pulsar jwt required
  clusters:
  - name: uscentral1-azure
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: uswest2-aws
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: eucentral1-aws
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: asiaeast2-gcp
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: useast1-gcp
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: useast2-aws
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
pulsarFunctionsConfig:
  intervalSeconds: 120
  masterToken: ''
  clusters:
  - name: uscentral1-azure
    triggerUrl: https://kafkaesque.io/api/v1/uscentral1-azure/functions/ming-luo/local-uscentral1-azure/for-monitor-function/trigger
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 15
      CeilingInMovingWindow: 5
  - name: uswest2-aws
    triggerUrl: https://kafkaesque.io/api/v1/uswest2-aws/functions/ming-luo/local-uswest2-aws/for-monitor-function/trigger
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 15
      CeilingInMovingWindow: 5
  - name: eucentral1-aws
    triggerUrl: https://kafkaesque.io/api/v1/eucentral1-aws/functions/ming-luo/local-eucentral1-aws/for-monitor-function/trigger
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 15
      CeilingInMovingWindow: 5
  - name: asiaeast2-gcp
    triggerUrl: https://kafkaesque.io/api/v1/asiaeast2-gcp/functions/ming-luo/local-asiaeast2-gcp/for-monitor-function/trigger
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 15
      CeilingInMovingWindow: 5
  - name: useast1-gcp
    triggerUrl: https://kafkaesque.io/api/v1/useast1-gcp/functions/ming-luo/local-useast1-gcp/for-monitor-function/trigger
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 15
      CeilingInMovingWindow: 5
  - name: useast2-aws
    triggerUrl: https://kafkaesque.io/api/v1/useast2-aws/functions/ming-luo/namespace2/for-monitor-function/trigger
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 15
      CeilingInMovingWindow: 5
pulsarPerfConfig:
  intervalSeconds: 120
  token: ''
  topicCfgs:
  - latencyBudgetMs: 360
    pulsarUrl: pulsar+ssl://useast1.gcp.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-useast1-gcp/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 30
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 2400
    pulsarUrl: pulsar+ssl://asiaeast2.gcp.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-asiaeast2-gcp/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 1850
    pulsarUrl: pulsar+ssl://eucentral1.aws.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-eucentral1-aws/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 480
    pulsarUrl: pulsar+ssl://uscentral1.azure.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-uscentral1-azure/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 480
    pulsarUrl: pulsar+ssl://uswest2.aws.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-uswest2-aws/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 360
    pulsarUrl: pulsar+ssl://useast2.aws.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-useast2-aws/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
